import { screen, render, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import KnownFor from '../KnownFor';

test('No roles for the person', () => {
    const knownFor = {
        cast: [],
        crew: [],
    };
    render(<KnownFor knownFor={knownFor} />);
    const renderedElement = screen.queryByTestId('knownFor');
    expect(renderedElement).toBeNull();
});

test('No duplicates', () => {
    const knownFor = {
        cast: [
            {
                genre_ids: [99],
                original_language: 'en',
                original_title: 'Inside Interstellar',
                poster_path: '/vemBplPKQhVe5cRWL7kxtgp15Vq.jpg',
                video: false,
                vote_average: 7.8,
                overview:
                    "Cast and crew of Christopher Nolan's 'Interstellar' discuss project origins, the film's imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film's music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations",
                release_date: '2015-03-31',
                vote_count: 4,
                title: 'Inside Interstellar',
                adult: false,
                backdrop_path: null,
                id: 157336,
                popularity: 1.894,
                character: 'Himself',
                credit_id: '5b1bcc479251414bc60213eb',
                order: 1,
                media_type: 'movie',
            },
        ],
        crew: [
            {
                adult: false,
                backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                genre_ids: [12, 18, 878],
                vote_count: 25837,
                original_language: 'en',
                original_title: 'Interstellar',
                poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                id: 157336,
                video: false,
                vote_average: 8.3,
                title: 'Interstellar',
                overview:
                    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
                release_date: '2014-11-05',
                popularity: 102.607,
                credit_id: '5e83abfad236e60017fd99ed',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                genre_ids: [12, 18, 878],
                vote_count: 25837,
                original_language: 'en',
                original_title: 'Interstellar',
                poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                id: 157336,
                video: false,
                vote_average: 8.3,
                title: 'Interstellar',
                overview:
                    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
                release_date: '2014-11-05',
                popularity: 102.607,
                credit_id: '52fe4bbf9251416c910e47ed',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
        ],
    };
    render(<KnownFor knownFor={knownFor} />, { wrapper: MemoryRouter });

    const renderedElement = screen.getByTestId('knownFor');
    expect(renderedElement).not.toBeNull();

    const images = within(renderedElement).getAllByTestId('image');
    expect(images.length).toBe(1);
});

test('No more than 10 results are shown', () => {
    const knownFor = {
        cast: [
            {
                adult: false,
                backdrop_path: '/v6EUsxCZBksSmcomBcXErJZWL2I.jpg',
                genre_ids: [99],
                id: 186567,
                original_language: 'en',
                original_title: 'Gotham Uncovered: Creation of a Scene',
                overview:
                    'Director Christopher Nolan and creative collaborators unmask the incredible detail and planning behind the film, including stunt staging, filmin in IMAX, the new Bat-Suit and Bat-Pod and other exclusive features.',
                poster_path: '/lAAwYAEnDXJoYt1V0DUBkLJK8sh.jpg',
                release_date: '2008-07-15',
                title: 'Gotham Uncovered: Creation of a Scene',
                video: false,
                vote_average: 6.5,
                vote_count: 6,
                popularity: 4.05,
                character: 'Himself',
                credit_id: '52fe4d009251416c7512c917',
                order: 0,
                media_type: 'movie',
            },
            {
                genre_ids: [99],
                original_language: 'en',
                original_title: 'Inside Interstellar',
                poster_path: '/vemBplPKQhVe5cRWL7kxtgp15Vq.jpg',
                video: false,
                vote_average: 7.8,
                overview:
                    "Cast and crew of Christopher Nolan's 'Interstellar' discuss project origins, the film's imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film's music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations",
                release_date: '2015-03-31',
                vote_count: 4,
                title: 'Inside Interstellar',
                adult: false,
                backdrop_path: null,
                id: 529107,
                popularity: 1.894,
                character: 'Himself',
                credit_id: '5b1bcc479251414bc60213eb',
                order: 1,
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [99],
                id: 790331,
                original_language: 'en',
                original_title:
                    'Looking at the World in a New Way: The Making of Tenet',
                overview:
                    "A look behind the scenes of Christopher Nolan's Tenet.",
                poster_path: '/bRsxj7tmQKNHRF4cc0vbBLlxCyt.jpg',
                release_date: '2020-12-15',
                title: 'Looking at the World in a New Way: The Making of Tenet',
                video: false,
                vote_average: 0.0,
                vote_count: 0,
                popularity: 2.253,
                character: 'Himself',
                credit_id: '609b859b8dbc33006e323a14',
                order: 1,
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/9PnKdVpdC7HaNjQLKPygHMT637e.jpg',
                genre_ids: [99],
                id: 29751,
                original_language: 'en',
                original_title:
                    'Batman Unmasked: The Psychology of the Dark Knight',
                overview:
                    'Delve into the world of Batman and the vigilante justice that he brought to the city of Gotham. Batman is a man who, after experiencing great tragedy, devotes his life to an ideal--but what happens when one man takes on the evil underworld alone? Examine why Batman is who he is--and explore how a boy scarred by tragedy becomes a symbol of hope to everyone else.',
                poster_path: '/e15wNHmLX7PJUo8lqzQRhwbX7PL.jpg',
                release_date: '2008-07-15',
                title: 'Batman Unmasked: The Psychology of the Dark Knight',
                video: false,
                vote_average: 7.6,
                vote_count: 34,
                popularity: 8.882,
                character: 'himself',
                credit_id: '52fe45f7c3a368484e0793e9',
                order: 4,
                media_type: 'movie',
            },
            {
                id: 243238,
                video: false,
                vote_count: 12,
                vote_average: 6.5,
                title: 'The Fire Rises: The Creation and Impact of The Dark Knight Trilogy',
                release_date: '2013-09-24',
                original_language: 'en',
                original_title:
                    'The Fire Rises: The Creation and Impact of The Dark Knight Trilogy',
                genre_ids: [99],
                backdrop_path: '/vc4BgDe25zwpdOm9908MAvjb3PU.jpg',
                adult: false,
                overview:
                    'This feature-length documentary delves into the trilogy, opening with the inspiration and vision for the new Batman films and inching its way toward the Rises finale and the culmination of nearly a decade of creative blood, sweat and tears. Candid, thoughtful and extensive, and comprised of revealing behind-the-scenes footage, countless interviews, audition tapes (with Christian Bale and Cillian Murphy doning the cape and cowl), and a narrative grip and momentum all its own, it leaves no stone unturned.',
                poster_path: '/y78UlBU4Y2HnEuvSW4V0A5DzP3C.jpg',
                popularity: 2.163,
                character: 'Himself',
                credit_id: '52fe4edbc3a36847f82ac56d',
                order: 5,
                media_type: 'movie',
            },
            {
                id: 227585,
                video: false,
                vote_count: 2,
                vote_average: 5.5,
                title: 'Tales from the Warner Bros. Lot',
                release_date: '2013-01-15',
                original_language: 'en',
                original_title: 'Tales from the Warner Bros. Lot',
                genre_ids: [99],
                backdrop_path: null,
                adult: false,
                overview:
                    'Actors, crew and executives who worked at Warner Bros. Pictures recall their days at the studio.',
                poster_path: '/k1Q1ayXdOb6H1emGtnGGwy63uPU.jpg',
                popularity: 0.721,
                character: 'Himself',
                credit_id: '52fe4ea99251416c7515e023',
                order: 7,
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/puznYtHv2zsZfRKWZbdqb9GrbgT.jpg',
                genre_ids: [99],
                id: 80337,
                original_language: 'en',
                original_title: 'These Amazing Shadows',
                overview:
                    'Tells the history and importance of The National Film Registry, a roll call of American cinema treasures that reflects the diversity of film, and indeed the American experience itself.',
                poster_path: '/jiby8Ilxlmbhv6elIf0qRMuaDdd.jpg',
                release_date: '2011-01-22',
                title: 'These Amazing Shadows',
                video: false,
                vote_average: 7.5,
                vote_count: 50,
                popularity: 4.646,
                character: 'Self',
                credit_id: '52fe47b99251416c91073b03',
                order: 10,
                media_type: 'movie',
            },
            {
                vote_average: 7.3,
                overview:
                    'Since the invention of cinema, the standard format for recording moving images has been film. Over the past two decades, a new form of digital filmmaking has emerged, creating a groundbreaking evolution in the medium. Keanu Reeves explores the development of cinema and the impact of digital filmmaking via in-depth interviews with Hollywood masters, such as James Cameron, David Fincher, David Lynch, Christopher Nolan, Martin Scorsese, George Lucas, Steven Soderbergh, and many more.',
                release_date: '2012-08-19',
                adult: false,
                backdrop_path: '/AkuDVdvopWHr2Vw3IBmfhlPk8Bx.jpg',
                vote_count: 214,
                genre_ids: [99],
                title: 'Side by Side',
                original_language: 'en',
                original_title: 'Side by Side',
                poster_path: '/qeeQ7rfTAXNYh4EqqdolFLkNwKM.jpg',
                id: 110354,
                video: false,
                popularity: 7.325,
                character: 'Self',
                credit_id: '52fe4ad2c3a36847f81e393d',
                order: 12,
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [99],
                id: 125231,
                original_language: 'en',
                original_title: 'The Batmobile',
                overview:
                    'Witness all five Batmobiles together for the first time in history. Dive deep into every aspect of the most awe-inspiring weapon in Batman’s arsenal as you journey through the birth and evolution of this technological marvel and cultural icon',
                poster_path: '/lhXI9v8g87JgBg5YiAL9Bpaonu7.jpg',
                release_date: '2012-07-16',
                title: 'The Batmobile',
                video: false,
                vote_average: 6.6,
                vote_count: 18,
                popularity: 1.811,
                character: 'Himself',
                credit_id: '52fe4abfc3a368484e164c6b',
                order: 13,
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/212dUHxXRdjylPqx3a3xIGtzjl9.jpg',
                genre_ids: [99],
                id: 734586,
                original_language: 'en',
                original_title: 'Joker: Put on a Happy Face',
                overview:
                    'Featuring interviews with filmmakers and industry legends, discover the origins and evolution of The Joker, and learn why The Clown Prince of Crime is universally hailed as the greatest comic-book supervillain of all time.',
                poster_path: '/am5Sst8LFmU0bhPrzU3km4RRy3J.jpg',
                release_date: '2020-08-18',
                title: 'Joker: Put on a Happy Face',
                video: false,
                vote_average: 8.6,
                vote_count: 18,
                popularity: 7.616,
                character: 'Self',
                credit_id: '5f3d323b9653f600369f56d6',
                order: 28,
                media_type: 'movie',
            },
            {
                backdrop_path: '/7ysNbTEttcxUq0MJwqWe3MO30Qy.jpg',
                first_air_date: '2015-04-20',
                genre_ids: [10767],
                id: 64711,
                name: 'StarTalk with Neil deGrasse Tyson',
                origin_country: ['US'],
                original_language: 'en',
                original_name: 'StarTalk with Neil deGrasse Tyson',
                overview:
                    'Host Neil deGrasse Tyson brings together celebrities, scientists and comedians to explore a variety of cosmic topics and collide pop culture with science in a way that late-night television has never seen before. Weekly topics range from popular science fiction, space travel, extraterrestrial life, the Big Bang, to the future of Earth and the environment. Tyson is an astrophysicist with a gifted ability to connect with everyone, inspiring us all to to "keep looking up."',
                poster_path: '/qCSXMlSNtgqTkrAYzK9dWPS7hHR.jpg',
                vote_average: 7.2,
                vote_count: 13,
                popularity: 5.212,
                character: 'Self',
                credit_id: '56746a4192514179dd000414',
                episode_count: 1,
                media_type: 'tv',
            },
        ],
        crew: [
            {
                video: false,
                vote_average: 6.7,
                id: 43629,
                overview:
                    'In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.',
                release_date: '1997-01-01',
                adult: false,
                backdrop_path: '/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg',
                vote_count: 311,
                genre_ids: [53, 14, 9648],
                title: 'Doodlebug',
                original_language: 'en',
                original_title: 'Doodlebug',
                poster_path: '/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg',
                popularity: 6.266,
                credit_id: '595e4934c3a368265d085a8f',
                department: 'Art',
                job: 'Set Designer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg',
                genre_ids: [99],
                id: 352114,
                original_language: 'en',
                original_title: 'Quay',
                overview:
                    'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                poster_path: '/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg',
                release_date: '2015-08-19',
                title: 'Quay',
                video: false,
                vote_average: 7.1,
                vote_count: 30,
                popularity: 2.367,
                credit_id: '5ad78d7dc3a368719c000d42',
                department: 'Camera',
                job: 'Director of Photography',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [],
                id: 456684,
                original_language: 'en',
                original_title: 'Larceny',
                overview:
                    "A man who likes to pick-pocket people, gets chased through the woods by the people he's trying to steal from",
                poster_path: '/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg',
                release_date: '1996-01-01',
                title: 'Larceny',
                video: false,
                vote_average: 5.6,
                vote_count: 5,
                popularity: 1.061,
                credit_id: '5e83ae2b24f2ce00187106ad',
                department: 'Camera',
                job: 'Director of Photography',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/kdSsUC9DpREwFFPeqPgAaxzE3UT.jpg',
                genre_ids: [10752, 28, 18],
                id: 374720,
                original_language: 'en',
                original_title: 'Dunkirk',
                overview:
                    'The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.',
                poster_path: '/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg',
                release_date: '2017-07-19',
                title: 'Dunkirk',
                video: false,
                vote_average: 7.5,
                vote_count: 12859,
                popularity: 46.36,
                credit_id: '5e83ab8fe33f830018359941',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                genre_ids: [12, 18, 878],
                vote_count: 25837,
                original_language: 'en',
                original_title: 'Interstellar',
                poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                id: 157336,
                video: false,
                vote_average: 8.3,
                title: 'Interstellar',
                overview:
                    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
                release_date: '2014-11-05',
                popularity: 102.607,
                credit_id: '5e83abfad236e60017fd99ed',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg',
                genre_ids: [99],
                id: 352114,
                original_language: 'en',
                original_title: 'Quay',
                overview:
                    'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                poster_path: '/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg',
                release_date: '2015-08-19',
                title: 'Quay',
                video: false,
                vote_average: 7.1,
                vote_count: 30,
                popularity: 2.367,
                credit_id: '5e83ac7688bbe60015a69864',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [],
                id: 505819,
                original_language: 'en',
                original_title:
                    'Cinema 16: European Short Films (U.S. Edition)',
                overview:
                    'A collection of short films by 16 European directors.',
                poster_path: '/rQ884232vYo3pbm0Ov1bCrMy6Zp.jpg',
                release_date: '2007-09-25',
                title: 'Cinema 16: European Short Films (U.S. Edition)',
                video: true,
                vote_average: 0.0,
                vote_count: 0,
                popularity: 1.092,
                credit_id: '5e83acc86e3b68001864b90b',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/mfJepkInUbiZ0mFXFhDNz8ko6Zr.jpg',
                genre_ids: [18, 9648, 53],
                id: 1124,
                original_language: 'en',
                original_title: 'The Prestige',
                overview:
                    'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.',
                poster_path: '/gcphM7ZLxS5HPeCZgjZobfz907x.jpg',
                release_date: '2006-10-19',
                title: 'The Prestige',
                video: false,
                vote_average: 8.2,
                vote_count: 11710,
                popularity: 25.875,
                credit_id: '5e83ad1888bbe60013a69c6b',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/q2CtXYjp9IlnfBcPktNkBPsuAEO.jpg',
                genre_ids: [9648, 53],
                id: 77,
                original_language: 'en',
                original_title: 'Memento',
                overview:
                    "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
                poster_path: '/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg',
                release_date: '2000-10-11',
                title: 'Memento',
                video: false,
                vote_average: 8.2,
                vote_count: 11020,
                popularity: 34.049,
                credit_id: '5e83ad65e33f83001435a709',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                video: false,
                vote_average: 6.7,
                id: 43629,
                overview:
                    'In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.',
                release_date: '1997-01-01',
                adult: false,
                backdrop_path: '/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg',
                vote_count: 311,
                genre_ids: [53, 14, 9648],
                title: 'Doodlebug',
                original_language: 'en',
                original_title: 'Doodlebug',
                poster_path: '/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg',
                popularity: 6.266,
                credit_id: '5e83ae1b24f2ce00137104f0',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/yzsegNpkRCPadnWmshrJzT3ardR.jpg',
                genre_ids: [28, 80, 18, 53],
                id: 49026,
                original_language: 'en',
                original_title: 'The Dark Knight Rises',
                overview:
                    "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
                release_date: '2012-07-16',
                title: 'The Dark Knight Rises',
                video: false,
                vote_average: 7.7,
                vote_count: 17801,
                popularity: 53.554,
                credit_id: '6044f4f8c4ad590058f9c3fd',
                department: 'Directing',
                job: 'Director',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/4kjQK9aanydnmMm6S6QOr1FLy6c.jpg',
                genre_ids: [18, 53],
                id: 11660,
                original_language: 'en',
                original_title: 'Following',
                overview:
                    'Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.',
                poster_path: '/5giub1nKK3sFRvZxmebe31scQOo.jpg',
                release_date: '1999-04-02',
                title: 'Following',
                video: false,
                vote_average: 7.2,
                vote_count: 1043,
                popularity: 9.623,
                credit_id: '52fe44739251416c7503532d',
                department: 'Editing',
                job: 'Editor',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [],
                id: 456684,
                original_language: 'en',
                original_title: 'Larceny',
                overview:
                    "A man who likes to pick-pocket people, gets chased through the woods by the people he's trying to steal from",
                poster_path: '/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg',
                release_date: '1996-01-01',
                title: 'Larceny',
                video: false,
                vote_average: 5.6,
                vote_count: 5,
                popularity: 1.061,
                credit_id: '595e4635c3a368265d085744',
                department: 'Editing',
                job: 'Editor',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: null,
                genre_ids: [],
                id: 804706,
                original_language: 'en',
                original_title: 'Tarantella',
                overview:
                    '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago, but it is currently not available to the public.',
                poster_path: null,
                release_date: '1989-12-31',
                title: 'Tarantella',
                video: false,
                vote_average: 0.0,
                vote_count: 0,
                popularity: 0.6,
                credit_id: '604a1920c8a5ac006f002fd7',
                department: 'Editing',
                job: 'Editor',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/4kjQK9aanydnmMm6S6QOr1FLy6c.jpg',
                genre_ids: [18, 53],
                id: 11660,
                original_language: 'en',
                original_title: 'Following',
                overview:
                    'Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.',
                poster_path: '/5giub1nKK3sFRvZxmebe31scQOo.jpg',
                release_date: '1999-04-02',
                title: 'Following',
                video: false,
                vote_average: 7.2,
                vote_count: 1043,
                popularity: 9.623,
                credit_id: '52fe44739251416c75035309',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/yzsegNpkRCPadnWmshrJzT3ardR.jpg',
                genre_ids: [28, 80, 18, 53],
                id: 49026,
                original_language: 'en',
                original_title: 'The Dark Knight Rises',
                overview:
                    "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
                release_date: '2012-07-16',
                title: 'The Dark Knight Rises',
                video: false,
                vote_average: 7.7,
                vote_count: 17801,
                popularity: 53.554,
                credit_id: '52fe4781c3a36847f8139893',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                genre_ids: [12, 18, 878],
                vote_count: 25837,
                original_language: 'en',
                original_title: 'Interstellar',
                poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                id: 157336,
                video: false,
                vote_average: 8.3,
                title: 'Interstellar',
                overview:
                    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
                release_date: '2014-11-05',
                popularity: 102.607,
                credit_id: '52fe4bbf9251416c910e47ed',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                poster_path: '/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
                id: 209112,
                overview:
                    'Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.',
                vote_average: 5.9,
                title: 'Batman v Superman: Dawn of Justice',
                vote_count: 14756,
                release_date: '2016-03-23',
                adult: false,
                backdrop_path: '/mX3WOJPBzzl4kj4xU5lL7qfD6C3.jpg',
                genre_ids: [28, 12, 14],
                video: false,
                original_language: 'en',
                original_title: 'Batman v Superman: Dawn of Justice',
                popularity: 72.176,
                credit_id: '553bf2ba925141125600a15d',
                department: 'Production',
                job: 'Executive Producer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/kdSsUC9DpREwFFPeqPgAaxzE3UT.jpg',
                genre_ids: [10752, 28, 18],
                id: 374720,
                original_language: 'en',
                original_title: 'Dunkirk',
                overview:
                    'The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.',
                poster_path: '/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg',
                release_date: '2017-07-19',
                title: 'Dunkirk',
                video: false,
                vote_average: 7.5,
                vote_count: 12859,
                popularity: 46.36,
                credit_id: '56cd9e759251415cda002182',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg',
                genre_ids: [99],
                id: 352114,
                original_language: 'en',
                original_title: 'Quay',
                overview:
                    'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                poster_path: '/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg',
                release_date: '2015-08-19',
                title: 'Quay',
                video: false,
                vote_average: 7.1,
                vote_count: 30,
                popularity: 2.367,
                credit_id: '595e478a925141225106bdac',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
                genre_ids: [28, 53, 878],
                original_language: 'en',
                original_title: 'Tenet',
                poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
                video: false,
                vote_average: 7.3,
                id: 577922,
                overview:
                    'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
                release_date: '2020-08-22',
                vote_count: 5314,
                title: 'Tenet',
                adult: false,
                popularity: 261.14,
                credit_id: '5da457b01967570011acf8d5',
                department: 'Production',
                job: 'Producer',
                media_type: 'movie',
            },
            {
                release_date: '2021-03-18',
                adult: false,
                backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
                title: "Zack Snyder's Justice League",
                genre_ids: [28, 12, 14, 878],
                original_language: 'en',
                original_title: "Zack Snyder's Justice League",
                id: 791373,
                vote_count: 5530,
                video: false,
                vote_average: 8.5,
                poster_path: '/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
                overview:
                    "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
                popularity: 1152.288,
                credit_id: '601461580816c70042848352',
                department: 'Production',
                job: 'Executive Producer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg',
                genre_ids: [99],
                id: 352114,
                original_language: 'en',
                original_title: 'Quay',
                overview:
                    'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                poster_path: '/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg',
                release_date: '2015-08-19',
                title: 'Quay',
                video: false,
                vote_average: 7.1,
                vote_count: 30,
                popularity: 2.367,
                credit_id: '5ad78d90c3a3687196000dad',
                department: 'Sound',
                job: 'Original Music Composer',
                media_type: 'movie',
            },
            {
                id: 155,
                original_language: 'en',
                overview:
                    'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
                poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                vote_count: 25118,
                video: false,
                adult: false,
                backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
                title: 'The Dark Knight',
                genre_ids: [18, 28, 80, 53],
                vote_average: 8.5,
                release_date: '2008-07-16',
                original_title: 'The Dark Knight',
                popularity: 60.005,
                credit_id: '52fe4220c3a36847f8005d03',
                department: 'Writing',
                job: 'Screenplay',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/mfJepkInUbiZ0mFXFhDNz8ko6Zr.jpg',
                genre_ids: [18, 9648, 53],
                id: 1124,
                original_language: 'en',
                original_title: 'The Prestige',
                overview:
                    'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.',
                poster_path: '/gcphM7ZLxS5HPeCZgjZobfz907x.jpg',
                release_date: '2006-10-19',
                title: 'The Prestige',
                video: false,
                vote_average: 8.2,
                vote_count: 11710,
                popularity: 25.875,
                credit_id: '52fe42e8c3a36847f802bef9',
                department: 'Writing',
                job: 'Screenplay',
                media_type: 'movie',
            },
            {
                video: false,
                vote_average: 6.7,
                id: 43629,
                overview:
                    'In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.',
                release_date: '1997-01-01',
                adult: false,
                backdrop_path: '/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg',
                vote_count: 311,
                genre_ids: [53, 14, 9648],
                title: 'Doodlebug',
                original_language: 'en',
                original_title: 'Doodlebug',
                poster_path: '/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg',
                popularity: 6.266,
                credit_id: '52fe4655c3a36847f80f96c9',
                department: 'Writing',
                job: 'Writer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/yzsegNpkRCPadnWmshrJzT3ardR.jpg',
                genre_ids: [28, 80, 18, 53],
                id: 49026,
                original_language: 'en',
                original_title: 'The Dark Knight Rises',
                overview:
                    "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
                release_date: '2012-07-16',
                title: 'The Dark Knight Rises',
                video: false,
                vote_average: 7.7,
                vote_count: 17801,
                popularity: 53.554,
                credit_id: '52fe4781c3a36847f813991b',
                department: 'Writing',
                job: 'Screenplay',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                genre_ids: [12, 18, 878],
                vote_count: 25837,
                original_language: 'en',
                original_title: 'Interstellar',
                poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                id: 157336,
                video: false,
                vote_average: 8.3,
                title: 'Interstellar',
                overview:
                    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
                release_date: '2014-11-05',
                popularity: 102.607,
                credit_id: '5505e4dac3a36862e900346c',
                department: 'Writing',
                job: 'Writer',
                media_type: 'movie',
            },
            {
                id: 417615,
                video: false,
                vote_count: 0,
                vote_average: 0.0,
                title: 'Memento',
                release_date: '',
                original_language: 'en',
                original_title: 'Memento',
                genre_ids: [9648, 53],
                backdrop_path: null,
                adult: false,
                overview:
                    "A remake of the 2000 film, 'Memento', which centers on a man suffering from short-term memory loss while trying to track down his wife's killer.",
                poster_path: null,
                popularity: 0.6,
                credit_id: '57e5557d9251411ab00038aa',
                department: 'Writing',
                job: 'Original Story',
                media_type: 'movie',
            },
            {
                release_date: '2010-07-15',
                id: 27205,
                vote_count: 29092,
                adult: false,
                backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
                vote_average: 8.3,
                genre_ids: [28, 878, 12],
                video: false,
                original_language: 'en',
                original_title: 'Inception',
                poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
                title: 'Inception',
                overview:
                    'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
                popularity: 63.601,
                credit_id: '5bcdbdfc9251416131020ee0',
                department: 'Writing',
                job: 'Writer',
                media_type: 'movie',
            },
            {
                adult: false,
                backdrop_path: '/rwywuA4irKO1zoMLBhJJaiUHv3U.jpg',
                genre_ids: [28, 18, 9648, 53],
                id: 14070,
                original_language: 'hi',
                original_title: 'गजनी',
                overview:
                    "Sanjay a rich tycoon suffering from short term memory loss due to being hit by a metal pole when trying to intervene on his girlfriend's murder. Because of this his memory can only last for 15 minutes and he doesn't remember events or incidents that have happened before in his life.",
                poster_path: '/8ib1Ddr8AuMa9sfVADjznzkih0x.jpg',
                release_date: '2008-12-25',
                title: 'Ghajini',
                video: false,
                vote_average: 6.9,
                vote_count: 274,
                popularity: 7.16,
                credit_id: '5dc10c45ef488900131775b9',
                department: 'Writing',
                job: 'Original Story',
                media_type: 'movie',
            },
            {
                id: 155,
                original_language: 'en',
                overview:
                    'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
                poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                vote_count: 25118,
                video: false,
                adult: false,
                backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
                title: 'The Dark Knight',
                genre_ids: [18, 28, 80, 53],
                vote_average: 8.5,
                release_date: '2008-07-16',
                original_title: 'The Dark Knight',
                popularity: 60.005,
                credit_id: '5f27d6a1d9403500375f670a',
                department: 'Writing',
                job: 'Story',
                media_type: 'movie',
            },
            {
                original_name: 'Hot Wheels City',
                id: 110163,
                name: 'Hot Wheels City',
                vote_count: 1,
                vote_average: 9.0,
                first_air_date: '2020-09-17',
                poster_path: null,
                genre_ids: [],
                original_language: 'en',
                backdrop_path: null,
                overview: 'The Hot wheels city',
                origin_country: [],
                popularity: 1.96,
                credit_id: '5f637072d236e6003677dfe3',
                department: 'Writing',
                episode_count: 2,
                job: "Writers' Production",
                media_type: 'tv',
            },
        ],
    };
    render(<KnownFor knownFor={knownFor} />, { wrapper: MemoryRouter });

    const renderedElement = screen.getByTestId('knownFor');
    expect(renderedElement).not.toBeNull();

    const images = within(renderedElement).getAllByTestId('image');
    expect(images.length).toBe(10);
});
